<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Monique Bactad" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting (SDS348) | It&#39;s ya boi, Norway again</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting (SDS348) | It&#39;s ya boi, Norway again</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<pre class="r"><code>knitr::opts_chunk$set(echo = TRUE, eval  =  TRUE, fig.align  =  &quot;center&quot;, warning  =  F, message  =  F,
tidy = TRUE, tidy.opts = list(width.cutoff = 60), R.options = list(max.print = 100))</code></pre>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>In this project, Norway, once again, shall be the focus. Here, I’ve retrieved 3 online data sets: Power Consumption, Coronavirus Pandemic Country Profile, and Mobility. The Power Consumption data set recorded hourly power consumption in megawatts (MW) for 15 European countries, and was uploaded by François Raucent on www.kaggle.com. I originally found the Coronavirus Pandemic Country Profile for Norway on <a href="https://ourworldindata.org/" class="uri">https://ourworldindata.org/</a>, and the data is also all collected on <a href="https://github.com/owid/covid-19-data/tree/master/public/data" class="uri">https://github.com/owid/covid-19-data/tree/master/public/data</a>. It details daily and summary statistics regarding information about COVID-19, such as cases, deaths, and vaccination. The Mobility was displayed on <a href="https://www.covid19data.no/" class="uri">https://www.covid19data.no/</a>, and it’s also available on <a href="https://github.com/thohan88/covid19-nor-data" class="uri">https://github.com/thohan88/covid19-nor-data</a>. The data displays trends of the usage of the types of transportation collected through Apple in various regions of Norway.</p>
<p>For this project, I’ll be isolating the date (March 7, 2020 to July 31, 2020, minus May 11-12, 2020), power consumption (MW), the number of new COVID cases, reproduction rate (the effective reproduction number of COVID- basically a measure of its transmission or the number of new infections generated by each case), the stringency index (a composite measure of the strictness of policy responses by the government on a scale of 0 to 100), and the trend values of transit (based off of a 100 baseline, I’m assuming, since the site and Apple did not give a lot of detail on how it’s measured).</p>
<p>After tidying the data and removing NAs, it will bring it to a total of 145 observations. I think this is an interesting mix of data that I would hope show the intensity of COVID and how it affected Norway power consumption, policy strictness-wise, and transportation.</p>
</div>
<div id="dataset-references" class="section level2">
<h2>Dataset References</h2>
<p>Western Europe Power Consumption (Five years of hourly electricity consumption of 15 European countries) - <a href="https://www.kaggle.com/francoisraucent/western-europe-power-consumption?select" class="uri">https://www.kaggle.com/francoisraucent/western-europe-power-consumption?select</a> = no.csv</p>
<p>Norway: Coronavirus Pandemic Country Profile - <a href="https://ourworldindata.org/coronavirus/country/norway#what-is-the-daily-number-of-confirmed-deaths" class="uri">https://ourworldindata.org/coronavirus/country/norway#what-is-the-daily-number-of-confirmed-deaths</a></p>
<p>Hannah Ritchie, Esteban Ortiz-Ospina, Diana Beltekian, Edouard Mathieu, Joe Hasell, Bobbie Macdonald, Charlie Giattino, Cameron Appel, Lucas Rodés-Guirao and Max Roser (2020) - “Coronavirus Pandemic (COVID-19)”. Published online at OurWorldInData.org. Retrieved from: ‘<a href="https://ourworldindata.org/coronavirus" class="uri">https://ourworldindata.org/coronavirus</a>’ [Online Resource]</p>
<p>COVID-19 Data Norway: Public data about the COVID-19-situation in Norway - <a href="https://www.covid19data.no/" class="uri">https://www.covid19data.no/</a></p>
</div>
<div id="tidying-data" class="section level2">
<h2>Tidying Data</h2>
<pre class="r"><code>library(readr)
NOpower &lt;- read_csv(&quot;no.csv&quot;, col_types = cols(load = col_number()))
NOpower &lt;- NOpower %&gt;% select(-end)
NOpower$start &lt;- as.Date(NOpower$start, format  =  &quot;%F&quot;)
NOpower &lt;- aggregate(. ~  start, data  =  NOpower, sum) %&gt;% rename(&quot;Date&quot;  =  &quot;start&quot;, &quot;Load (MW)&quot;  =  &quot;load&quot;)

library(readr)
NOstats &lt;- read_csv(&quot;owid-covid-data.csv&quot;, col_types = cols(date = col_date(format = &quot;%m/%d/%y&quot;)))
NOstats &lt;- NOstats %&gt;% rename(&quot;Date&quot;  =  &quot;date&quot;) %&gt;% filter(location %in% &quot;Norway&quot;) %&gt;% select(c(&quot;Date&quot;, &quot;new_cases&quot;, &quot;reproduction_rate&quot;, &quot;stringency_index&quot;)) %&gt;% mutate_at(c(&quot;new_cases&quot;), ~replace(., is.na(.), 0)) 

NOdata &lt;- NOpower %&gt;% full_join(NOstats, by = &quot;Date&quot;) %&gt;% na.omit()
NOdata %&gt;% summarize(max(`reproduction_rate`), min(`reproduction_rate`))</code></pre>
<pre><code>##   max(reproduction_rate) min(reproduction_rate)
## 1                   3.06                   0.61</code></pre>
<pre class="r"><code>NOdata &lt;- NOdata %&gt;% mutate(Infection_intensity = case_when(`reproduction_rate`&gt;2.243333 ~ &quot;high&quot;, `reproduction_rate`&lt;= 2.243333 &amp; 1.426667&lt;= `reproduction_rate` ~ &quot;med&quot;, `reproduction_rate`&lt;1.426667 ~ &quot;low&quot;))</code></pre>
<pre class="r"><code>library(readxl)
NOmobility &lt;- read_excel(&quot;mobility.xlsx&quot;, col_types  =  c(&quot;text&quot;, &quot;text&quot;, &quot;text&quot;, &quot;text&quot;, &quot;numeric&quot;, &quot;text&quot;, &quot;text&quot;, &quot;numeric&quot;))
NOmobility$date &lt;- as.Date(NOmobility$date, format  =  &quot;%F&quot;) 
NOmobility &lt;- NOmobility %&gt;% rename(&quot;Date&quot;  =  &quot;date&quot;) %&gt;% select(-c(&quot;geo_type&quot;, &quot;country&quot;, &quot;sub-region&quot;, &quot;alternative_name&quot;)) %&gt;% filter(region ==  &quot;Norway&quot;) %&gt;% filter(transportation_type !=  &quot;walking&quot;) %&gt;% filter(transportation_type !=  &quot;driving&quot;)
NOmobility &lt;- aggregate(val ~ Date + transportation_type, data  =  NOmobility, FUN  =  sum)
NOmobility &lt;- NOmobility %&gt;% rename(&quot;Transit Value&quot;  =  &quot;val&quot;, &quot;Transportation&quot;  =  &quot;transportation_type&quot;) %&gt;% select(-c(&quot;Transportation&quot;))

NOdata &lt;- NOdata %&gt;% full_join(NOmobility, by = &quot;Date&quot;) %&gt;% filter(Date !=  &quot;2020-05-11&quot; &amp; Date !=  &quot;2020-05-12&quot;) %&gt;% na.omit()
NOdata$Transit_trend &lt;- ifelse(NOdata$`Transit Value`&gt;100,&quot;Increase&quot;,&quot;Decrease&quot;)

head(NOdata)</code></pre>
<pre><code>## Date Load (MW) new_cases reproduction_rate
stringency_index Infection_intensity
## 1 2020-03-07 433313 39 2.93 11.11 high
## 2 2020-03-08 405005 29 2.93 11.11 high
## 3 2020-03-09 420752 29 2.99 11.11 high
## 4 2020-03-10 432851 195 3.06 14.81 high
## 5 2020-03-11 421793 198 2.91 20.37 high
## 6 2020-03-12 428652 104 2.68 40.74 high
## Transit Value Transit_trend
## 1 111.71 Increase
## 2 100.39 Increase
## 3 93.39 Decrease
## 4 88.36 Decrease
## 5 78.62 Decrease
## 6 56.74 Decrease</code></pre>
<p>(I don’t know why but tidying data is fun now that I know how to do it haha)</p>
</div>
<div id="manova" class="section level2">
<h2>MANOVA</h2>
<pre class="r"><code>num.vars &lt;- cbind(NOdata$`Load (MW)`, NOdata$stringency_index, NOdata$`Transit Value`, NOdata$new_cases)
man1&lt;-manova( num.vars ~ Infection_intensity, data  =  NOdata)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Infection_intensity 2 0.85177 25.963 8 280 &lt; 2.2e-16 ***
## Residuals 142
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary(aov(num.vars ~ NOdata$Infection_intensity))</code></pre>
<pre><code>## Response 1 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## NOdata$Infection_intensity 2 9.4363e+10 4.7182e+10
21.367 7.718e-09 ***
## Residuals 142 3.1355e+11 2.2081e+09
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response 2 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## NOdata$Infection_intensity 2 8135 4067.3 17.26 1.951e-07
***
## Residuals 142 33463 235.7
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response 3 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## NOdata$Infection_intensity 2 1719 859.47 1.0999 0.3357
## Residuals 142 110964 781.44
##
## Response 4 :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## NOdata$Infection_intensity 2 86979 43489 7.1249 0.001125
**
## Residuals 142 866743 6104
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(NOdata$`Load (MW)`,NOdata$Infection_intensity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  NOdata$`Load (MW)` and NOdata$Infection_intensity 
## 
##     high    low   
## low 9.3e-09 -     
## med 0.0007  0.0048
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(NOdata$stringency_index,NOdata$Infection_intensity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: NOdata$stringency_index and
NOdata$Infection_intensity
##
## high low
## low 3.1e-08 -
## med 1.9e-05 0.35
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(NOdata$new_cases,NOdata$Infection_intensity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  NOdata$new_cases and NOdata$Infection_intensity 
## 
##     high   low   
## low 0.0136 -     
## med 0.7714 0.0028
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#Overall Type I Error Rate
1-.95^14</code></pre>
<pre><code>## [1] 0.512325</code></pre>
<pre class="r"><code>#Bonferroni Adjustment
.05/14</code></pre>
<pre><code>## [1] 0.003571429</code></pre>
<p>MANOVA had a p-value less than 0.05, thus there is at least one variable that has a significant mean difference. Transit Value is not significant, but the others are based on the 4 univariate ANOVAS. Using only the variables that showed a mean difference, 9 total pairwise t-tests were run. About 51.2325% of tests have a Type I error when unadjusted. The corrected threshold was 0.003571429. Using this, 6 of the 9 pairwise t-tests were significant: 3 tests for Load (MW), 2 for the stringency index, and 1 for new cases. Overall, I do think that the MONVA assumptions were largely met. I do fear, though, that because this data is taken with COVID-19 in mind, some of the variables may be too correlated.</p>
</div>
<div id="test-and-plot" class="section level2">
<h2>– Test and Plot</h2>
<pre class="r"><code>randmeans&lt;-vector()
randmeans2&lt;-vector()

for(i in 1:5000){
randsamp&lt;-sample(NOdata[NOdata$Transit_trend == &quot;Increase&quot;,]$stringency_index,replace = T)
randmeans[i]&lt;-mean(randsamp)
randsamp2&lt;-sample(NOdata[NOdata$Transit_trend == &quot;Decrease&quot;,]$stringency_index,replace = T)
randmeans2[i]&lt;-mean(randsamp2)  
}
randmeanDiff&lt;-randmeans2-randmeans
quantile(randmeanDiff,c(.025, .975))</code></pre>
<pre><code>##     2.5%    97.5% 
## 17.31765 24.89957</code></pre>
<pre class="r"><code>ggplot()+geom_histogram(aes(randmeanDiff))+geom_vline(xintercept = quantile(randmeanDiff,c(.025,.975)))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>t.test(NOdata[NOdata$Transit_trend == &quot;Increase&quot;,]$stringency_index, NOdata[NOdata$Transit_trend == &quot;Decrease&quot;,]$stringency_index, var.equal  =  F)</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: NOdata[NOdata$Transit_trend == &quot;Increase&quot;,
]$stringency_index and NOdata[NOdata$Transit_trend ==
&quot;Decrease&quot;, ]$stringency_index
## t = -10.817, df = 125.54, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## -24.93551 -17.22262
## sample estimates:
## mean of x mean of y
## 38.99706 60.07613</code></pre>
<p>I did a randomization test on the mean difference for average stringency index for when Transit trends increased or decreased (based on th 100 value baseline). The null hypothesis was that the average stringency index was the same for when the transit trend increased or decreased. The alternative hypothesis was that the avergae of the stringency index differs between the increase or decrease of transit trends. After the randomization test, it shows that 95% of the average stringency index when transit trends increased or decreased have a mean difference between a stringency index of 17.36317 and a stringency index of 24.97875. A t-test showed the significance with the p-value of 2.2e-16.</p>
</div>
<div id="linear-regression-model" class="section level2">
<h2>Linear Regression Model</h2>
<pre class="r"><code>library(lmtest)
library(sandwich)

NOdata$LoadCent &lt;- NOdata$`Load (MW)` - mean(NOdata$`Load (MW)`, na.rm  =  T)
NOdata$ReproCent &lt;- NOdata$reproduction_rate - mean(NOdata$reproduction_rate, na.rm  =  T)
NOdata$TransitCent &lt;- NOdata$`Transit Value` - mean(NOdata$`Transit Value`, na.rm  =  T)

lin.fit&lt;-lm(data  =  NOdata, stringency_index~LoadCent*ReproCent*TransitCent)
summary(lin.fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = stringency_index ~ LoadCent * ReproCent *
TransitCent,
## data = NOdata)
##
## Residuals:
## Min 1Q Median 3Q Max
## -10.1663 -1.9915 0.0147 2.1504 9.1956
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 4.976e+01 1.166e+00 42.661 &lt; 2e-16 ***
## LoadCent 1.672e-06 1.829e-05 0.091 0.9273
## ReproCent -1.698e+01 2.470e+00 -6.875 2.01e-10 ***
## TransitCent -4.762e-01 3.255e-02 -14.629 &lt; 2e-16 ***
## LoadCent:ReproCent 2.602e-05 3.332e-05 0.781 0.4363
## LoadCent:TransitCent -3.868e-06 6.170e-07 -6.269
4.41e-09 ***
## ReproCent:TransitCent 4.153e-01 7.644e-02 5.433 2.46e-07
***
## LoadCent:ReproCent:TransitCent -1.545e-06 7.815e-07
-1.977 0.0501 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 3.779 on 137 degrees of freedom
## Multiple R-squared: 0.953, Adjusted R-squared: 0.9506
## F-statistic: 396.6 on 7 and 137 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>ggplot(NOdata, aes(stringency_index, reproduction_rate)) + geom_point() + geom_smooth(method  =  &quot;lm&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids&lt;-lin.fit$residuals
fitvals&lt;-lin.fit$fitted.values

ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept  =  0, color  =  &#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.98408, p-value = 0.09194</code></pre>
<pre class="r"><code>coeftest(lin.fit, vcov = vcovHC(lin.fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 4.9761e+01 1.1625e+00 42.8062 &lt; 2.2e-16 ***
## LoadCent 1.6722e-06 2.2904e-05 0.0730 0.9419
## ReproCent -1.6983e+01 2.7672e+00 -6.1373 8.497e-09 ***
## TransitCent -4.7620e-01 3.9340e-02 -12.1047 &lt; 2.2e-16
***
## LoadCent:ReproCent 2.6020e-05 3.7252e-05 0.6985 0.4861
## LoadCent:TransitCent -3.8683e-06 5.8789e-07 -6.5801
9.188e-10 ***
## ReproCent:TransitCent 4.1527e-01 7.8859e-02 5.2660
5.269e-07 ***
## LoadCent:ReproCent:TransitCent -1.5449e-06 1.0298e-06
-1.5002 0.1359
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>I wanted to see if the mean centered Load (MW), reproduction rate of COVID and the Transit value had any affect on the stringincy index. After running the linear regression and summary of the model, for every 1 megawatt increase in Load, the stringency index would increase by 1.6722e-06. For every 1 point increase in the reproduction rate, the stringency index would decrease by 1.6983e+01. For every 1 point increase in transit value, the stringency index would decrease by 4.7620e-01. For every 1 unit increase in the interaction of load and would increase the stringency index by 2.6020e-05. For every 1 unit increase in the interaction of load and transit value would decrease the stringency index by 3.8683e-06. For every 1 unit increase in the interaction of reproduction rate and transit value would decrease the stringency index by 4.1527e-01. Lastly, for every 1 unit increase in the interaction of reproduction rate, transit value, and load would decrease the stringency index by 1.5449e-06. However, LoadCent, LoadCent:ReproCent, LoadCent:ReproCent:TransitCent have p-values greater then 0.05. The model explains 95.3% of variation in the outcome. Visually, the data definitely appears sus but it does show linearity and seems homoskedastic, but normality does not fit. However, the Shapiro-Wilk normality test has a p-value of 0.09194, which is greater than 0.05. After recomputing with robust standard errors, there was no change in coefficients nor p-values.</p>
</div>
<div id="linear-regression-model-with-boostrapped-standard-errors" class="section level2">
<h2>Linear Regression Model with Boostrapped Standard Errors</h2>
<p>Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</p>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {  
  boot_dat &lt;- sample_frac(NOdata, replace = T)
fit2 &lt;- lm(stringency_index~LoadCent*ReproCent*TransitCent, data = boot_dat) 
coef(fit2)
}) 

samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>## (Intercept) LoadCent ReproCent TransitCent
LoadCent:ReproCent LoadCent:TransitCent
## 1 1.185783 2.197481e-05 2.827825 0.03788547 3.874023e-05
5.954521e-07
## ReproCent:TransitCent LoadCent:ReproCent:TransitCent
## 1 0.08218773 1.013627e-06</code></pre>
<pre class="r"><code>summary(lin.fit)$coef[,1:2]</code></pre>
<pre><code>##                                     Estimate   Std. Error
## (Intercept)                     4.976108e+01 1.166435e+00
## LoadCent                        1.672157e-06 1.828915e-05
## ReproCent                      -1.698332e+01 2.470417e+00
## TransitCent                    -4.761974e-01 3.255051e-02
## LoadCent:ReproCent              2.601979e-05 3.332358e-05
## LoadCent:TransitCent           -3.868352e-06 6.170116e-07
## ReproCent:TransitCent           4.152711e-01 7.644149e-02
## LoadCent:ReproCent:TransitCent -1.544896e-06 7.815033e-07</code></pre>
<pre class="r"><code>bptest(lin.fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  lin.fit
## BP = 16.075, df = 7, p-value = 0.02444</code></pre>
<p>While the robust and original SEs were nearly the same, the bootstrapped SEs are more different than either. The p-value that assesses for homoskedacity in the original model is was 0.02444. Because of the dissimilarity in both the original and bootstraped SEs, it is fair to assume that the p-values for the bootstrapped model won’t be close to what was calculated originally.</p>
</div>
<div id="logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<pre class="r"><code>NOdata$Transit_trend &lt;- as.factor(NOdata$Transit_trend)
fit3 &lt;- glm(Transit_trend~stringency_index+reproduction_rate, data=NOdata, family= binomial(link=&quot;logit&quot;))

exp(coef(fit3))</code></pre>
<pre><code>##       (Intercept)  stringency_index reproduction_rate 
##      2.325843e+04      8.249704e-01      1.238830e-01</code></pre>
<pre class="r"><code>prob&lt;-predict(fit3,type = &quot;response&quot;)

class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}

class_diag(prob,NOdata$Transit_trend)</code></pre>
<pre><code>## acc sens spec ppv auc
## Increase 0.7931034 0.5882353 0.8558559 0.5555556
0.8766561</code></pre>
<pre class="r"><code>table(predict = as.numeric(prob&gt;.5),truth = NOdata$Transit_trend)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict Decrease Increase Sum
##     0         95       14 109
##     1         16       20  36
##     Sum      111       34 145</code></pre>
<pre class="r"><code>NOdata$logit&lt;-predict(fit3)
NOdata$outcome&lt;-factor(NOdata$Transit_trend,levels = c(&quot;Increase&quot;,&quot;Decrease&quot;))

ggplot(NOdata,aes(logit, fill = outcome))+geom_density(alpha = .3)+ geom_vline(xintercept = 0,lty = 2)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-8-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
ROCplot&lt;-ggplot(NOdata)+geom_roc(aes(d = outcome,m = prob), n.cuts = 0) 
ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-8-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8766561</code></pre>
<p>Here, I used a logistic regression to predict the transit trend using the stringency index and reproduction rate. The exponentiated coefficients show that for every 1 point increase of the stringency index and the reproduction rate, the odds of a stroke increase by 8.249704e-01 and 1.238830e-01, respectively. After the classification diagnostics, we have an accuracy of 0.7931034, a sensitivity of 0.5882353, a specificity of 0.8558559, a precision of 0.5555556, and an AUC of 0.8766561. The ROCplot has the same AUC. I believe this shows a pretty good model of the predictability of the transit trend with the stringency index and reproduction rate since the AUC is decent.</p>
</div>
<div id="logistic-regression-cont." class="section level2">
<h2>Logistic Regression cont.</h2>
<pre class="r"><code>NOdata.orig &lt;- NOdata[,c(2:8)]
NOdata.orig$Transit_trend &lt;- as.factor(NOdata.orig$Transit_trend)

#Logisitic Regression featuring the rest of the available predictors
fit4 &lt;- glm(Transit_trend~., data=NOdata.orig, family= binomial(link=&quot;logit&quot;))

prob2&lt;-predict(fit4,type = &quot;response&quot;)

#Classification Diagnostics
class_diag(prob2,NOdata.orig$Transit_trend)</code></pre>
<pre><code>##          acc sens spec ppv auc
## Increase   1    1    1   1   1</code></pre>
<pre class="r"><code>#10-fold CV
k = 10

data &lt;- NOdata.orig %&gt;% sample_frac
folds &lt;- ntile(1:nrow(data),n = 10) 

diags&lt;-NULL
for(i in 1:k){
  train &lt;- data[folds!= i,] 
  test &lt;- data[folds == i,] 
  truth &lt;- test$Transit_trend 
  
  fit5 &lt;- glm(Transit_trend~., data = NOdata.orig, family = &quot;binomial&quot;)
  probs &lt;- predict(fit5, newdata = test, type = &quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}

#Classification Diagnostics for 10-fold CV
summarize_all(diags,mean)</code></pre>
<pre><code>##   acc sens spec ppv auc
## 1   1    1    1   1   1</code></pre>
<pre class="r"><code>library(glmnet)

#LASSO
y&lt;-as.matrix(NOdata.orig$Transit_trend)
x&lt;-model.matrix(Transit_trend~.,data = NOdata.orig)[,-1]

cv&lt;-cv.glmnet(x,y,family = &quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family = &quot;binomial&quot;,lambda = cv$lambda.1se)

coef(lasso)</code></pre>
<pre><code>## 8 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                 s0
## (Intercept)            -49.5779535
## `Load (MW)`              .        
## new_cases                .        
## reproduction_rate        .        
## stringency_index         .        
## Infection_intensitylow  -1.2640183
## Infection_intensitymed   0.8188897
## `Transit Value`          0.5100945</code></pre>
<pre class="r"><code>#10-fold CV with LASSO selected variables
k = 10

data &lt;- NOdata.orig %&gt;% sample_frac
folds &lt;- ntile(1:nrow(data),n = 10)

diags&lt;-NULL
for(i in 1:k){
  train &lt;- data[folds!= i,]
  test &lt;- data[folds == i,]
  truth &lt;- test$Transit_trend
  
  fit5 &lt;- glm(Transit_trend ~ `Transit Value`+ Infection_intensity , data = NOdata.orig, family = &quot;binomial&quot;)
  probs &lt;- predict(fit5, newdata = test, type = &quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}

#Classification Diagnostics for LASSO 10-fold CV
summarize_all(diags,mean)</code></pre>
<pre><code>##   acc sens spec ppv auc
## 1   1    1    1   1   1</code></pre>
<p>Here, I am now using 6 predictors from the dataset to see if they significantly predict the transit trend. The resulting classification diagnostics had all values of 1. I’m still not sure how this happened, even after trying out with changing codes past this assignment’s due date. Performing a 10-fold CV also gives all the diagnostics a value of 1. After conducting a LASSO, the non-zero variables were the Transit Value and the infection intensity of low and medium. However, from the lasso-selected CV, all values again were 1. I’m not sure, maybe it’s due to the fact that I had to change Transit trend to a factor class, but I had to so that the logistic regression could work. But, this data was fun to work with anyways!</p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
